apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deploy
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: 10
  selector:
    matchLabels:
      app: hello-world
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-pod
        image: tomcoolpxl/node-web-app:1.0
        ports:
        - containerPort: 8080
